server:
  port: 8060
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /client2


security:
    oauth2:
      client:
        clientId: c2
        clientSecret: 123456
        user-authorization-uri: http://127.0.0.1:8888/server/oauth/authorize
        access-token-uri: http://127.0.0.1:8888/server/oauth/token

      resource:
        jwt:
          key-uri: http://127.0.0.1:8888/server/oauth/token_key #配置的访问密钥身份认证
#
#spring:
#  security:
#    oauth2:
#      client:
#        clientId: c2
#        clientSecret: 123456
#        accessTokenUri: http://127.0.0.1:8888/server/oauth/access_token
#        userAuthorizationUri: http://127.0.0.1:8888/server/dialog/oauth
#        tokenName: oauth_token
#        authenticationScheme: query
#        clientAuthenticationScheme: form
#      resource:
#        jwt:
#          key-uri: http://127.0.0.1:8888/server/oauth/token_key